version: '3.7'

services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy

  traefik:
    image: traefik:v2.5
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8585" # Custom Traefik HTTP port
      - "--entrypoints.websecure.address=:5443" # Custom Traefik HTTPS port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy

  whoami:
    image: containous/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`dev.acumenus.net`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      - proxy

  whoami2:
    image: containous/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami2.rule=Host(`broadsea.acumenus.net`)"
      - "traefik.http.routers.whoami2.entrypoints=web"
    networks:
      - proxy

networks:
  proxy:
    name: proxy

volumes:
  caddy_data:
  caddy_config:

