### Caddy as Prime RP + Traefik as sub RP for Broadsea + Ngnix as sub RP for Perseus
### Heimdall as Launch Page for Parthenon

version: '3.7'

services:
  caddy:
    image: caddy:latest
    container_name: "parthenon-caddy"
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy

##################################################
#
#
#   PARTHENON LAUNCH PAGE
#
#
##################################################

  heimdall:
    image: "linuxserver/heimdall:latest"
    container_name: "heimdall"
    restart: "always"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York # Replace with your timezone
      - APP_NAME=Parthenon
    volumes:
      - "./heimdall:/config"
      - "./heimdall/favicons/favicon-16x16.png:/var/www/localhost/heimdall/public/favicon-16x16.png"
      - "./heimdall/favicons/favicon-32x32.png:/var/www/localhost/heimdall/public/favicon-32x32.png"
      - "./heimdall/favicons/favicon.ico:/var/www/localhost/heimdall/public/favicon.ico"
    networks:
      - proxy

##################################################
#
#   BROADSEA CORE
#     *** edit .env file per inline instructions
#
##################################################




##################################################
#
#   PERSEUS
#
###################################################


##################################################
#
#
#   PARTHENON NETWORKS AND VOLUMES
#
#
##################################################

networks:
  proxy:
    name: proxy

volumes:
  caddy_data:
  caddy_config:
